arch:
   - ppc64le
   - amd64
os: linux
dist: xenial
language: erlang
before_install:
    - if [ "$TRAVIS_ARCH" = "ppc64le" ]; then sudo apt-get update; sudo apt-get install rebar; fi


script: make all

_latest_otp_release: &latest_otp_release
  otp_release: 23.1.1

jobs:
  include:
    - name: Coverage Report
      language: erlang
      <<: *latest_otp_release
      env: COVER=true
      script: make test
      after_success:
        - for f in _build/test/covertool/*.xml; do cp "$f" $(basename "${f%.xml}.coverage.xml"); done
        - bash <(curl -s https://codecov.io/bash)
    - name: Test Examples
      language: erlang
      <<: *latest_otp_release
      script: make test-examples
    - otp_release: 23.1.1
    - otp_release: 23.0
    - otp_release: 22.3
    - otp_release: 22.0
    - otp_release: 21.3
    - otp_release: 21.0
    - otp_release: 20.3
    - otp_release: 20.0
    - otp_release: 19.3
# Disable otp_release 23.1.1 & 19.3 as these releases are not supported on Ubuntu16.04 for arch: ppc64le
jobs: 
 exclude:
    - arch: ppc64le
    otp_release: 23.1.1
    - arch: ppc64le
    otp_release: 19.3
    - arch: ppc64le
    otp_release: 20.0
    - arch: ppc64le
    otp_release: 21.3


cache:
   directories:
   - .plt
